/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:8d181591-f7fb-4042-80e6-0a5c434ae87d",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_F8d2P2y5v",
    "aws_user_pools_web_client_id": "4qds5t5lq3i8uatnlpgfar37hj",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://zxuq7df3irb2bjbjcfn2zvsoxi.appsync-api.ap-south-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-south-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-fakeApiId123456",
    "aws_user_files_s3_bucket": "officetodosd8b61f5a9ae24b00ad5d25989d1a0a1c134122-dev",
    "aws_user_files_s3_bucket_region": "ap-south-1"
};

export default awsmobile;